// ═══════════════════════════════════════════════
//  CHARACTERS — نسخة الدارجة 🇲🇦  (Dofus-style)
// ═══════════════════════════════════════════════

const CHARACTERS = [
  {
    id:           'siyasi',
    emoji:        '🎩',
    name:         'السياسي',
    title:        'Le Politique',
    color:        '#FFD700',
    bg:           'linear-gradient(135deg,#2a1e00,#3d2c00)',
    border:       '#FFD700',
    ability:      'immuneTrap',
    abilityLabel: '🛡️ محصّن من الفخاخ',
    abilityDesc:  'كيما المسؤول — والو ما يوصلو، ولا ضريبة ولا باراج!',
    speedDots:    3,
  },
  {
    id:           'fqih',
    emoji:        '📖',
    name:         'الفقيه',
    title:        'Le Fqih',
    color:        '#38A0FF',
    bg:           'linear-gradient(135deg,#001a2e,#002a4a)',
    border:       '#38A0FF',
    ability:      'bonusAnswer',
    abilityLabel: '🧠 +150 على الجواب الصحيح',
    abilityDesc:  'العلم قوة — كل جواب صح كيجيب 150 نقطة بدل 100.',
    speedDots:    2,
  },
  {
    id:           'addaw',
    emoji:        '🏃',
    name:         'العدّاء',
    title:        "L'Addaw",
    color:        '#2ECC71',
    bg:           'linear-gradient(135deg,#001a0e,#002a18)',
    border:       '#2ECC71',
    ability:      'speed',
    abilityLabel: '⚡ سرعة مضاعفة',
    abilityDesc:  'أسرع من الخبر — يتحرك ضعف سرعة الآخرين.',
    speedDots:    5,
  },
  {
    id:           'tajir',
    emoji:        '💰',
    name:         'التاجر',
    title:        'Le Marchand',
    color:        '#FF8C00',
    bg:           'linear-gradient(135deg,#1a0e00,#2a1600)',
    border:       '#FF8C00',
    ability:      'bonusDouble',
    abilityLabel: '⭐ البونوص x2',
    abilityDesc:  'البيزنس في دمو — كل نجمة أو صندوق كيجيب ضعف النقاط.',
    speedDots:    3,
  },
  {
    id:           'chiikha',
    emoji:        '🎭',
    name:         'الشيخة',
    title:        'La Chiikha',
    color:        '#FF3FA4',
    bg:           'linear-gradient(135deg,#1a0010,#2a0018)',
    border:       '#FF3FA4',
    ability:      'fastInteract',
    abilityLabel: '😈 كولداون الإنتراكشن ÷2',
    abilityDesc:  'لسانها سيف — تعاقب وتشتم ضعف المرات.',
    speedDots:    4,
  },
  {
    id:           'jinn',
    emoji:        '🧿',
    name:         'الجنّي',
    title:        'Le Djinn',
    color:        '#B44FFF',
    bg:           'linear-gradient(135deg,#0e001a,#18002a)',
    border:       '#B44FFF',
    ability:      'wideFov',
    abilityLabel: '👁️ رؤية موسّعة دايما',
    abilityDesc:  'شايف كل شيء — الضباب أقل، يرى أبعد من الآخرين.',
    speedDots:    2,
  },
];
